source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OneAPM_Example', :exclusive => true do
  pod 'OneAPM', :path => '../'
end

target 'OneAPM_Tests', :exclusive => true do
  pod 'OneAPM', :path => '../'

  
end
